### ISSUE TITLE
Implement breadcrumbs?

### ISSUE THREAD

**Issue by axelra82** [chas-academy/u02-redesign-unit7#29]
# Would breadcrumbs be a nice touch? 🤷‍♂️
Opening a discussion regarding implementing a breadcrumb in the header 🤓 
Although we won't be making all the sub-pages for this site, it's still a nice design element to have for a site that could (in reality) have at least a couple levels of depth 🤔

Thoughts? 😃

**PS**. Added the _suggestion_ label. Thinking that it would be good to have something for general discussions 👍

**Comment by stenwall** [comment]
I think it would be great to have breadcrumbs! Just really easy and simple with arrows under the header.

**Comment by axelra82** [comment]
Cool! My suggestion is that we start by trying to finish everything as planned until Wednesday and take it from there. If we have time on Thursday/Friday we can look in to this as well 💯 👍 

Thoughts @Oskar-Mikael @AndersLilienberg 😄

**Comment by Oskar-Mikael** [comment]
I tried creating just a very simple breadcrumb layout. There might be a smarter and more universal way to implement it. I have just written in a paragraph and added an anchor.
https://gyazo.com/ddf2b4e3844290cf05324a6f0ec2bd7d
`<p class="breadcrumbs">
            <a href="/index.html">Hem</a> &nbsp; > &nbsp; <span class="link-active">Om Oss</span>
        </p>`
