### ISSUE TITLE
A good place for media content

### ISSUE THREAD

**Issue by axelra82** [chas-academy/u02-redesign-unit7#31]
I've found what looks to be the [official MYH YouTube channel](https://www.youtube.com/channel/UC8iPn0eKy-5vQ6Mx_-ep-KA) 😊

Considering that we have to embed media in our project, this could be a great place to get that content 👍

What do you guys think? Any other suggestions for media sources? 🤓

**Comment by stenwall** [comment]
Perfect! Maybe on the "om-oss"-page?

**Comment by axelra82** [comment]
Yup, sounds like a good place for it 👍

**Comment by stenwall** [comment]
Okay I think this video is great: https://youtu.be/WHXqKTtAdLM
Maybe for the contact page? Or "Om oss"?

This one is also nice and could definitely work somewhere: https://youtu.be/2rx8GVrdhoQ

I also think the colors they use in these videos are much nicer than the colors they're using right now. What do you say? I think it gives a much more soft and nice impression without compromising with the familiarity of the current design.

[![Screenshot-2020-10-26-at-19.52.41.md.png](https://imgshare.io/images/2020/10/26/Screenshot-2020-10-26-at-19.52.41.md.png)](https://imgshare.io/image/NY4x2H)

[![Screenshot-2020-10-26-at-19.54.25.md.png](https://imgshare.io/images/2020/10/26/Screenshot-2020-10-26-at-19.54.25.md.png)](https://imgshare.io/image/NY4UXd)

What do you say? I've extracted some of the colors that I like and really think would work:

[![Screenshot-2020-10-26-at-20.18.26.md.png](https://imgshare.io/images/2020/10/26/Screenshot-2020-10-26-at-20.18.26.md.png)](https://imgshare.io/image/NY4f5Y)

Some more shades and tints (you can click on all of the images to see them larger):

[![Screenshot-2020-10-26-at-20.06.59.md.png](https://imgshare.io/images/2020/10/26/Screenshot-2020-10-26-at-20.06.59.md.png)](https://imgshare.io/image/NY4kLj)
[![Screenshot-2020-10-26-at-20.06.46.md.png](https://imgshare.io/images/2020/10/26/Screenshot-2020-10-26-at-20.06.46.md.png)](https://imgshare.io/image/NY4G5S)
[![Screenshot-2020-10-26-at-20.07.54.md.png](https://imgshare.io/images/2020/10/26/Screenshot-2020-10-26-at-20.07.54.md.png)](https://imgshare.io/image/NY4Jll)
[![Screenshot-2020-10-26-at-20.08.08.md.png](https://imgshare.io/images/2020/10/26/Screenshot-2020-10-26-at-20.08.08.md.png)](https://imgshare.io/image/NY4ejt)
[![Screenshot-2020-10-26-at-20.09.19.md.png](https://imgshare.io/images/2020/10/26/Screenshot-2020-10-26-at-20.09.19.md.png)](https://imgshare.io/image/NY4LJ8)
[![Screenshot-2020-10-26-at-20.09.33.md.png](https://imgshare.io/images/2020/10/26/Screenshot-2020-10-26-at-20.09.33.md.png)](https://imgshare.io/image/NY4o6w)
[![Screenshot-2020-10-26-at-20.08.29.md.png](https://imgshare.io/images/2020/10/26/Screenshot-2020-10-26-at-20.08.29.md.png)](https://imgshare.io/image/NY40Vx)
[![Screenshot-2020-10-26-at-20.08.38.md.png](https://imgshare.io/images/2020/10/26/Screenshot-2020-10-26-at-20.08.38.md.png)](https://imgshare.io/image/NY4KXK)
[![Screenshot-2020-10-26-at-20.11.16.md.png](https://imgshare.io/images/2020/10/26/Screenshot-2020-10-26-at-20.11.16.md.png)](https://imgshare.io/image/NY4Dhy)
[![Screenshot-2020-10-26-at-20.11.23.md.png](https://imgshare.io/images/2020/10/26/Screenshot-2020-10-26-at-20.11.23.md.png)](https://imgshare.io/image/NY44L4)
[![Screenshot-2020-10-26-at-20.09.56.md.png](https://imgshare.io/images/2020/10/26/Screenshot-2020-10-26-at-20.09.56.md.png)](https://imgshare.io/image/NY41vZ)
[![Screenshot-2020-10-26-at-20.10.06.md.png](https://imgshare.io/images/2020/10/26/Screenshot-2020-10-26-at-20.10.06.md.png)](https://imgshare.io/image/NY4glc)
[![Screenshot-2020-10-26-at-20.10.31.md.png](https://imgshare.io/images/2020/10/26/Screenshot-2020-10-26-at-20.10.31.md.png)](https://imgshare.io/image/NY4tZe)
[![Screenshot-2020-10-26-at-20.10.39.md.png](https://imgshare.io/images/2020/10/26/Screenshot-2020-10-26-at-20.10.39.md.png)](https://imgshare.io/image/NY4Fg6)

**Comment by axelra82** [comment]
@stenwall Liking the colors 👍 Let's see how/where we can use them for a different styling approach 👌

**Comment by axelra82** [comment]
Took out the color hex's you provided in the image @stenwall  and ran them through a naming process for colors, so we can call the something as well 😄 

- **Yellows**
  - _Icterine_
  #f8f066

  - _Yellow Pantone_
  #fee51e

- **Blues**
  - Raisin Black
  #19212c

  - Prussian Blue
  #263a52

  - Shadow Blue
  #7891b6

- **Reds**
  - Burnished Brown
  #9b777d


- **Greens**
  - Dark Slate Gray
  #394d45

Let's pocket this for our daily group chat today and see what everyone thinks 👍

**Comment by axelra82** [comment]
Ive added all the above colors as **variables and background classes** in my latest pull request #39 @stenwall @Oskar-Mikael just so we don't do the same thing twice/double work 😂 🤓

**Comment by stenwall** [comment]
@axelra82 Great! Let's hope the others like it too :)

**Comment by axelra82** [comment]
Feels like we can close this now. We have embedded video on about page and implemented new colors across the board from this issue as well 👌
