### ISSUE TITLE
Issues/questions for Kristian on Friday

### ISSUE THREAD

**Issue by stenwall** [chas-academy/u02-redesign-unit7#49]
An issue for discussions on what to take up with Kristian on Friday. We'll probably won't know exactly what we need help with until Friday, but I think we can start on a list right now, and if we solve things on it ourselves before the meeting, we just remove them from the list! 😄

**EDIT**
Add your question below using '_- [ ] Question_' for things that we need answered by Kristian this Friday:
- [x] Can we use our current component loader for production? **I.e.** is that "to much" javascript? 🤷‍♂️ Where is "the line" on JS? 🤔 😂 
- [x] We also have JS for our menu, search (which of course isn't a requirement), contact form etc. Are these ok? 🤔 
- [x] How basic does the accessibility need to be? 
- [x] About the contact form, is the current one we have ok?
- [x] Mobile testing, will it be done in "developer mode" or actual devices?
- [x] Parallax; Pure CSS, JS? What is expected and what is "OK"? 🤔 
- [x] CSS animation! We have one, very simple in the search function. However, the search function is not part of the requirements. Will it "count" or do we need something more "visible"?

**Comment by axelra82** [comment]
**Sounds great!** 👍
Since we all have **total access here**, we can simply edit your initial comment with - [ ] to make a list of things that we need answers to 🤓 Just to keep it visible and clean 😄
